; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
<<<<<<< HEAD

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
	mirs240x/micro_ros_arduino@^2.0.7-humble
	paulstoffregen/PWMServo@^2.1
=======
>>>>>>> bb22b368558d82fc99aa663ed459fe6ada4d3aa5
